/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica3;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Point;

/**
 *
 * @author carlo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

        private Point punto;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
    }
        @Override
        public void paint (Graphics g)
        {
            super.paint(g);
            g.fillOval(punto.x-25, punto.y-25, 50, 50);
                    
        }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Boton1 = new javax.swing.JButton();
        Boton2 = new javax.swing.JButton();

        FormListener formListener = new FormListener();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1920, 1080));
        addMouseListener(formListener);

        Boton1.setText("Boton1");
        Boton1.addMouseMotionListener(formListener);
        Boton1.addMouseListener(formListener);
        getContentPane().add(Boton1, java.awt.BorderLayout.PAGE_START);

        Boton2.setText("Boton2");
        Boton2.addMouseListener(formListener);
        Boton2.addActionListener(formListener);
        getContentPane().add(Boton2, java.awt.BorderLayout.PAGE_END);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseListener, java.awt.event.MouseMotionListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == Boton2) {
                VentanaPrincipal.this.Boton2ActionPerformed(evt);
            }
        }

        public void mouseClicked(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Boton1) {
                VentanaPrincipal.this.Boton1MouseClicked(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseClicked(evt);
            }
            else if (evt.getSource() == Boton2) {
                VentanaPrincipal.this.Boton2MouseClicked(evt);
            }
        }

        public void mouseEntered(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Boton1) {
                VentanaPrincipal.this.Boton1MouseEntered(evt);
            }
        }

        public void mouseExited(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Boton1) {
                VentanaPrincipal.this.Boton1MouseExited(evt);
            }
        }

        public void mousePressed(java.awt.event.MouseEvent evt) {
        }

        public void mouseReleased(java.awt.event.MouseEvent evt) {
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == Boton1) {
                VentanaPrincipal.this.Boton1MouseDragged(evt);
            }
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
        }
    }// </editor-fold>//GEN-END:initComponents

    private void Boton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseClicked
        // TODO add your handling code here:
        Boton1.setBackground(Color.red);
    }//GEN-LAST:event_Boton1MouseClicked

    private void Boton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseEntered
        // TODO add your handling code here:
        Boton1.setBackground(Color.blue);
    }//GEN-LAST:event_Boton1MouseEntered

    private void Boton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseExited
        // TODO add your handling code here:
        Boton1.setBackground(Color.green);
    }//GEN-LAST:event_Boton1MouseExited

    private void Boton1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton1MouseDragged
        // TODO add your handling code here:
        Boton1.setBackground(Color.yellow);
    }//GEN-LAST:event_Boton1MouseDragged

    private void formMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseClicked
        // TODO add your handling code here:
        this.setTitle("Practica 3");
        Boton1.setBackground(Color.white);
        Boton2.setBackground(Color.white);
        
       
        punto =  evt.getPoint();
              
        this.repaint();
        
        
        
    }//GEN-LAST:event_formMouseClicked

    private void Boton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton2ActionPerformed
        // TODO add your handling code here:
        Boton2.setBackground(Color.pink);
    }//GEN-LAST:event_Boton2ActionPerformed

    private void Boton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Boton2MouseClicked
        // TODO add your handling code here:
        Boton2.setBackground(Color.red);
    }//GEN-LAST:event_Boton2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton1;
    private javax.swing.JButton Boton2;
    // End of variables declaration//GEN-END:variables
}
