/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica10;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Image;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseMotionAdapter;
import java.awt.geom.AffineTransform;
import java.awt.image.AffineTransformOp;
import java.awt.image.BufferedImage;
import java.awt.image.ByteLookupTable;
import java.awt.image.ColorModel;
import java.awt.image.ConvolveOp;
import java.awt.image.Kernel;
import java.awt.image.LookupOp;
import java.awt.image.LookupTable;
import java.awt.image.RescaleOp;
import java.awt.image.WritableRaster;
import java.io.File;
import static java.lang.Math.abs;
import java.util.Vector;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.event.InternalFrameAdapter;
import javax.swing.filechooser.FileNameExtensionFilter;
import sm.image.KernelProducer;
import sm.image.LookupTableProducer;

/**
 *
 * @author carlo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    private BufferedImage imgFuente = null;
    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(1280, 720);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesHerramientas = new javax.swing.ButtonGroup();
        ventanaTamanio = new javax.swing.JDialog();
        alto = new javax.swing.JSpinner();
        ancho = new javax.swing.JSpinner();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        botonCancelar = new javax.swing.JButton();
        botonRecortar = new javax.swing.JButton();
        botonRedimensionar = new javax.swing.JButton();
        panelImageOp = new javax.swing.JPanel();
        PanelCentral = new javax.swing.JPanel();
        barraOpcionesImagen = new javax.swing.JToolBar();
        panelBrillo = new javax.swing.JPanel();
        sliderBrillo = new javax.swing.JSlider();
        panelFiltros = new javax.swing.JPanel();
        seleccionMascara = new javax.swing.JComboBox<>();
        panelContraste = new javax.swing.JPanel();
        botonContraste = new javax.swing.JButton();
        botonOscurecer = new javax.swing.JButton();
        botonIluminar = new javax.swing.JButton();
        botonNegativo = new javax.swing.JButton();
        botonIluminarZonasOscuras = new javax.swing.JButton();
        panelCuadratico = new javax.swing.JPanel();
        botonCuadratica = new javax.swing.JButton();
        sliderCuadratico = new javax.swing.JSlider();
        panelRotacion = new javax.swing.JPanel();
        sliderRotacion = new javax.swing.JSlider();
        boton90 = new javax.swing.JButton();
        boton180 = new javax.swing.JButton();
        boton270 = new javax.swing.JButton();
        panelEscalado = new javax.swing.JPanel();
        botonAmpliar = new javax.swing.JButton();
        botonReduccion = new javax.swing.JButton();
        escritorio = new javax.swing.JDesktopPane();
        panelHerramientas = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        botonNuevo = new javax.swing.JButton();
        botonAbrir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        botonDuplicar = new javax.swing.JButton();
        barraFormas = new javax.swing.JToolBar();
        botonPunto = new javax.swing.JToggleButton();
        botonLinea = new javax.swing.JToggleButton();
        botonRectangulo = new javax.swing.JToggleButton();
        botonElipse = new javax.swing.JToggleButton();
        botonSeleccionar = new javax.swing.JToggleButton();
        barraAtributos = new javax.swing.JToolBar();
        Color colores[] ={Color.BLACK, Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW, Color.WHITE};
        botonDesplegableColores = new javax.swing.JComboBox<>(colores);
        botonGrosor = new javax.swing.JSpinner();
        botonRelleno = new javax.swing.JToggleButton();
        botonTransparencia = new javax.swing.JToggleButton();
        botonAlisar = new javax.swing.JToggleButton();
        botonRecorte = new javax.swing.JToggleButton();
        botonVolcado = new javax.swing.JButton();
        botonAplicarOperaciones = new javax.swing.JToggleButton();
        panelEstados = new javax.swing.JPanel();
        barraCoordenadas = new javax.swing.JLabel();
        barraEstado = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuBarraEstado = new javax.swing.JCheckBoxMenuItem();
        menuBarraFormas = new javax.swing.JCheckBoxMenuItem();
        menuBarraAtributos = new javax.swing.JCheckBoxMenuItem();
        menuTamanio = new javax.swing.JMenuItem();
        menuImagen = new javax.swing.JMenu();
        menuRescaleOp = new javax.swing.JMenuItem();
        menuConvolveOp = new javax.swing.JMenuItem();
        menuAffineTransfomOp = new javax.swing.JMenuItem();
        menuLookupOp = new javax.swing.JMenuItem();

        FormListener formListener = new FormListener();

        ventanaTamanio.setSize(new java.awt.Dimension(400, 400));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Ancho");
        jLabel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Alto");
        jLabel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        botonCancelar.setText("Cancelar");
        botonCancelar.addActionListener(formListener);
        jPanel2.add(botonCancelar);

        botonRecortar.setText("Recortar");
        botonRecortar.addActionListener(formListener);
        jPanel2.add(botonRecortar);

        botonRedimensionar.setText("Redimensionar");
        botonRedimensionar.addActionListener(formListener);
        jPanel2.add(botonRedimensionar);

        javax.swing.GroupLayout ventanaTamanioLayout = new javax.swing.GroupLayout(ventanaTamanio.getContentPane());
        ventanaTamanio.getContentPane().setLayout(ventanaTamanioLayout);
        ventanaTamanioLayout.setHorizontalGroup(
            ventanaTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaTamanioLayout.createSequentialGroup()
                .addGap(111, 111, 111)
                .addGroup(ventanaTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(77, 77, 77)
                .addGroup(ventanaTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(alto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        ventanaTamanioLayout.setVerticalGroup(
            ventanaTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ventanaTamanioLayout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(ventanaTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(ancho, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(ventanaTamanioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(alto, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(formListener);

        PanelCentral.setLayout(new java.awt.BorderLayout());

        barraOpcionesImagen.setRollover(true);

        panelBrillo.setBorder(javax.swing.BorderFactory.createTitledBorder("Brillo"));
        panelBrillo.setLayout(new java.awt.BorderLayout());

        sliderBrillo.setMaximum(255);
        sliderBrillo.setMinimum(-255);
        sliderBrillo.setToolTipText("Brillo");
        sliderBrillo.setValue(0);
        sliderBrillo.addChangeListener(formListener);
        sliderBrillo.addFocusListener(formListener);
        panelBrillo.add(sliderBrillo, java.awt.BorderLayout.CENTER);

        barraOpcionesImagen.add(panelBrillo);
        panelBrillo.getAccessibleContext().setAccessibleName("");

        panelFiltros.setBorder(javax.swing.BorderFactory.createTitledBorder("Filtros"));
        panelFiltros.setLayout(new java.awt.BorderLayout());

        seleccionMascara.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Media", "Binomial", "Enfoque", "Relieve", "Fronteras", "Media Horizontal", "Media Diagonal" }));
        seleccionMascara.setToolTipText("Filtros");
        seleccionMascara.addActionListener(formListener);
        panelFiltros.add(seleccionMascara, java.awt.BorderLayout.CENTER);

        barraOpcionesImagen.add(panelFiltros);

        panelContraste.setBorder(javax.swing.BorderFactory.createTitledBorder("Contraste"));
        panelContraste.setLayout(new java.awt.GridLayout(1, 0));

        botonContraste.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\contraste.png")); // NOI18N
        botonContraste.setToolTipText("Contraste");
        botonContraste.addActionListener(formListener);
        panelContraste.add(botonContraste);

        botonOscurecer.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\oscurecer.png")); // NOI18N
        botonOscurecer.setToolTipText("Oscurecer");
        botonOscurecer.addActionListener(formListener);
        panelContraste.add(botonOscurecer);

        botonIluminar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\iluminar.png")); // NOI18N
        botonIluminar.setToolTipText("Iluminar");
        botonIluminar.addActionListener(formListener);
        panelContraste.add(botonIluminar);

        botonNegativo.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\negativo.png")); // NOI18N
        botonNegativo.setToolTipText("Negativo");
        botonNegativo.addActionListener(formListener);
        panelContraste.add(botonNegativo);

        botonIluminarZonasOscuras.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\acllararzonasoscuras.png")); // NOI18N
        botonIluminarZonasOscuras.setToolTipText("Iluminar Zonas Oscuras");
        botonIluminarZonasOscuras.addActionListener(formListener);
        panelContraste.add(botonIluminarZonasOscuras);

        barraOpcionesImagen.add(panelContraste);

        panelCuadratico.setBorder(javax.swing.BorderFactory.createTitledBorder("Funcion Cuadratica"));
        panelCuadratico.setLayout(new java.awt.GridLayout(1, 0));

        botonCuadratica.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\cuadratica.png")); // NOI18N
        botonCuadratica.setToolTipText("Funcion Cuadratica");
        botonCuadratica.setPreferredSize(new java.awt.Dimension(30, 30));
        botonCuadratica.addActionListener(formListener);
        panelCuadratico.add(botonCuadratica);

        sliderCuadratico.setMaximum(255);
        sliderCuadratico.setValue(128);
        sliderCuadratico.setPreferredSize(new java.awt.Dimension(100, 26));
        panelCuadratico.add(sliderCuadratico);

        barraOpcionesImagen.add(panelCuadratico);

        panelRotacion.setBorder(javax.swing.BorderFactory.createTitledBorder("Rotacion"));

        sliderRotacion.setMaximum(360);
        sliderRotacion.setMinorTickSpacing(90);
        sliderRotacion.setPaintTicks(true);
        sliderRotacion.setToolTipText("Rotacion");
        sliderRotacion.setValue(0);
        sliderRotacion.setPreferredSize(new java.awt.Dimension(150, 26));
        sliderRotacion.addChangeListener(formListener);
        sliderRotacion.addFocusListener(formListener);
        panelRotacion.add(sliderRotacion);

        boton90.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\rotacion90.png")); // NOI18N
        boton90.addActionListener(formListener);
        panelRotacion.add(boton90);

        boton180.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\rotacion180.png")); // NOI18N
        boton180.addActionListener(formListener);
        panelRotacion.add(boton180);

        boton270.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\rotacion270.png")); // NOI18N
        boton270.addActionListener(formListener);
        panelRotacion.add(boton270);

        barraOpcionesImagen.add(panelRotacion);

        panelEscalado.setBorder(javax.swing.BorderFactory.createTitledBorder("Escalado"));
        panelEscalado.setLayout(new java.awt.GridLayout(1, 0));

        botonAmpliar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\aumentar.png")); // NOI18N
        botonAmpliar.addActionListener(formListener);
        panelEscalado.add(botonAmpliar);

        botonReduccion.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\disminuir.png")); // NOI18N
        botonReduccion.addActionListener(formListener);
        panelEscalado.add(botonReduccion);

        barraOpcionesImagen.add(panelEscalado);

        PanelCentral.add(barraOpcionesImagen, java.awt.BorderLayout.SOUTH);

        escritorio.addMouseMotionListener(formListener);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1785, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 149, Short.MAX_VALUE)
        );

        PanelCentral.add(escritorio, java.awt.BorderLayout.CENTER);

        getContentPane().add(PanelCentral, java.awt.BorderLayout.CENTER);

        panelHerramientas.setLayout(new javax.swing.BoxLayout(panelHerramientas, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(150, 32));

        botonNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\nuevo.png")); // NOI18N
        botonNuevo.setToolTipText("Nuevo");
        botonNuevo.setFocusable(false);
        botonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonNuevo.addActionListener(formListener);
        jToolBar1.add(botonNuevo);

        botonAbrir.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\abrir.png")); // NOI18N
        botonAbrir.setToolTipText("Abrir");
        botonAbrir.setFocusable(false);
        botonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAbrir.addActionListener(formListener);
        jToolBar1.add(botonAbrir);

        botonGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\guardar.png")); // NOI18N
        botonGuardar.setToolTipText("Guardar");
        botonGuardar.setFocusable(false);
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGuardar.addActionListener(formListener);
        jToolBar1.add(botonGuardar);

        botonDuplicar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\duplicar.png")); // NOI18N
        botonDuplicar.setToolTipText("Duplicar Ventana");
        botonDuplicar.setFocusable(false);
        botonDuplicar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonDuplicar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonDuplicar.addActionListener(formListener);
        jToolBar1.add(botonDuplicar);

        panelHerramientas.add(jToolBar1);

        barraFormas.setRollover(true);
        barraFormas.setPreferredSize(new java.awt.Dimension(200, 32));

        GrupoBotonesHerramientas.add(botonPunto);
        botonPunto.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\punto.png")); // NOI18N
        botonPunto.setToolTipText("Punto");
        botonPunto.setFocusable(false);
        botonPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPunto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPunto.addActionListener(formListener);
        barraFormas.add(botonPunto);

        GrupoBotonesHerramientas.add(botonLinea);
        botonLinea.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\linea.png")); // NOI18N
        botonLinea.setToolTipText("Linea");
        botonLinea.setFocusable(false);
        botonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLinea.addActionListener(formListener);
        barraFormas.add(botonLinea);

        GrupoBotonesHerramientas.add(botonRectangulo);
        botonRectangulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\rectangulo.png")); // NOI18N
        botonRectangulo.setToolTipText("Rectangulo");
        botonRectangulo.setFocusable(false);
        botonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRectangulo.addActionListener(formListener);
        barraFormas.add(botonRectangulo);

        GrupoBotonesHerramientas.add(botonElipse);
        botonElipse.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\elipse.png")); // NOI18N
        botonElipse.setToolTipText("Elipse");
        botonElipse.setFocusable(false);
        botonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonElipse.addActionListener(formListener);
        barraFormas.add(botonElipse);

        GrupoBotonesHerramientas.add(botonSeleccionar);
        botonSeleccionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\seleccion.png")); // NOI18N
        botonSeleccionar.setToolTipText("Seleccionar");
        botonSeleccionar.setFocusable(false);
        botonSeleccionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSeleccionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSeleccionar.addActionListener(formListener);
        barraFormas.add(botonSeleccionar);

        panelHerramientas.add(barraFormas);

        barraAtributos.setRollover(true);
        barraAtributos.setPreferredSize(new java.awt.Dimension(250, 32));

        botonDesplegableColores.setToolTipText("Colores");
        botonDesplegableColores.setRenderer(new ColorCellRender());
        botonDesplegableColores.addActionListener(formListener);
        barraAtributos.add(botonDesplegableColores);

        botonGrosor.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));
        botonGrosor.setToolTipText("Grosor");
        botonGrosor.setPreferredSize(new java.awt.Dimension(60, 26));
        botonGrosor.addChangeListener(formListener);
        barraAtributos.add(botonGrosor);

        botonRelleno.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\rellenar.png")); // NOI18N
        botonRelleno.setToolTipText("Relleno");
        botonRelleno.setFocusable(false);
        botonRelleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRelleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRelleno.addActionListener(formListener);
        barraAtributos.add(botonRelleno);

        botonTransparencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\transparencia.png")); // NOI18N
        botonTransparencia.setToolTipText("Transparencia");
        botonTransparencia.setFocusable(false);
        botonTransparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTransparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonTransparencia.addActionListener(formListener);
        barraAtributos.add(botonTransparencia);

        botonAlisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\alisar.png")); // NOI18N
        botonAlisar.setToolTipText("Alisado");
        botonAlisar.setFocusable(false);
        botonAlisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAlisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAlisar.addActionListener(formListener);
        barraAtributos.add(botonAlisar);

        botonRecorte.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica8\\images\\recortar.png")); // NOI18N
        botonRecorte.setToolTipText("Efecto Ventana");
        botonRecorte.setFocusable(false);
        botonRecorte.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRecorte.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRecorte.addActionListener(formListener);
        barraAtributos.add(botonRecorte);

        botonVolcado.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica8\\images\\volcado.png")); // NOI18N
        botonVolcado.setToolTipText("Volcado");
        botonVolcado.setFocusable(false);
        botonVolcado.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonVolcado.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonVolcado.addActionListener(formListener);
        barraAtributos.add(botonVolcado);

        botonAplicarOperaciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica10\\images\\aplicar.png")); // NOI18N
        botonAplicarOperaciones.setToolTipText("Aplicar Operaciones a Formas");
        botonAplicarOperaciones.setFocusable(false);
        botonAplicarOperaciones.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAplicarOperaciones.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        barraAtributos.add(botonAplicarOperaciones);

        panelHerramientas.add(barraAtributos);

        getContentPane().add(panelHerramientas, java.awt.BorderLayout.PAGE_START);

        panelEstados.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        panelEstados.setPreferredSize(new java.awt.Dimension(1550, 25));
        panelEstados.setLayout(new java.awt.BorderLayout());

        barraCoordenadas.setText("Coordenadas");
        panelEstados.add(barraCoordenadas, java.awt.BorderLayout.EAST);

        barraEstado.setText("Barra de Estado");
        panelEstados.add(barraEstado, java.awt.BorderLayout.LINE_START);

        getContentPane().add(panelEstados, java.awt.BorderLayout.PAGE_END);

        menuArchivo.setText("Archivo");

        menuNuevo.setText("Nuevo");
        menuNuevo.addActionListener(formListener);
        menuArchivo.add(menuNuevo);

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(formListener);
        menuArchivo.add(menuAbrir);

        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(formListener);
        menuArchivo.add(menuGuardar);

        Menu.add(menuArchivo);

        menuEdicion.setText("Edicion");

        menuBarraEstado.setSelected(true);
        menuBarraEstado.setText("Ver barra de estado");
        menuBarraEstado.addActionListener(formListener);
        menuEdicion.add(menuBarraEstado);

        menuBarraFormas.setSelected(true);
        menuBarraFormas.setText("Ver barra de formas");
        menuBarraFormas.addActionListener(formListener);
        menuEdicion.add(menuBarraFormas);

        menuBarraAtributos.setSelected(true);
        menuBarraAtributos.setText("Ver barra de atributos");
        menuBarraAtributos.addActionListener(formListener);
        menuEdicion.add(menuBarraAtributos);

        menuTamanio.setText("Cambiar Tamaño");
        menuTamanio.addActionListener(formListener);
        menuEdicion.add(menuTamanio);

        Menu.add(menuEdicion);

        menuImagen.setText("Imagen");

        menuRescaleOp.setText("Operador RescaleOp");
        menuRescaleOp.addActionListener(formListener);
        menuImagen.add(menuRescaleOp);

        menuConvolveOp.setText("Operador ConvolveOp");
        menuConvolveOp.addActionListener(formListener);
        menuImagen.add(menuConvolveOp);

        menuAffineTransfomOp.setText("Operador AffineTransfomOp");
        menuAffineTransfomOp.addActionListener(formListener);
        menuImagen.add(menuAffineTransfomOp);

        menuLookupOp.setText("Operador LookupOp");
        menuLookupOp.addActionListener(formListener);
        menuImagen.add(menuLookupOp);

        Menu.add(menuImagen);

        setJMenuBar(Menu);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.FocusListener, java.awt.event.MouseMotionListener, javax.swing.event.ChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == seleccionMascara) {
                VentanaPrincipal.this.seleccionMascaraActionPerformed(evt);
            }
            else if (evt.getSource() == botonContraste) {
                VentanaPrincipal.this.botonContrasteActionPerformed(evt);
            }
            else if (evt.getSource() == botonOscurecer) {
                VentanaPrincipal.this.botonOscurecerActionPerformed(evt);
            }
            else if (evt.getSource() == botonIluminar) {
                VentanaPrincipal.this.botonIluminarActionPerformed(evt);
            }
            else if (evt.getSource() == botonNegativo) {
                VentanaPrincipal.this.botonNegativoActionPerformed(evt);
            }
            else if (evt.getSource() == botonCuadratica) {
                VentanaPrincipal.this.botonCuadraticaActionPerformed(evt);
            }
            else if (evt.getSource() == boton90) {
                VentanaPrincipal.this.boton90ActionPerformed(evt);
            }
            else if (evt.getSource() == boton180) {
                VentanaPrincipal.this.boton180ActionPerformed(evt);
            }
            else if (evt.getSource() == boton270) {
                VentanaPrincipal.this.boton270ActionPerformed(evt);
            }
            else if (evt.getSource() == botonAmpliar) {
                VentanaPrincipal.this.botonAmpliarActionPerformed(evt);
            }
            else if (evt.getSource() == botonReduccion) {
                VentanaPrincipal.this.botonReduccionActionPerformed(evt);
            }
            else if (evt.getSource() == botonNuevo) {
                VentanaPrincipal.this.botonNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == botonAbrir) {
                VentanaPrincipal.this.botonAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == botonGuardar) {
                VentanaPrincipal.this.botonGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == botonDuplicar) {
                VentanaPrincipal.this.botonDuplicarActionPerformed(evt);
            }
            else if (evt.getSource() == botonPunto) {
                VentanaPrincipal.this.botonPuntoActionPerformed(evt);
            }
            else if (evt.getSource() == botonLinea) {
                VentanaPrincipal.this.botonLineaActionPerformed(evt);
            }
            else if (evt.getSource() == botonRectangulo) {
                VentanaPrincipal.this.botonRectanguloActionPerformed(evt);
            }
            else if (evt.getSource() == botonElipse) {
                VentanaPrincipal.this.botonElipseActionPerformed(evt);
            }
            else if (evt.getSource() == botonSeleccionar) {
                VentanaPrincipal.this.botonSeleccionarActionPerformed(evt);
            }
            else if (evt.getSource() == botonDesplegableColores) {
                VentanaPrincipal.this.botonDesplegableColoresActionPerformed(evt);
            }
            else if (evt.getSource() == botonRelleno) {
                VentanaPrincipal.this.botonRellenoActionPerformed(evt);
            }
            else if (evt.getSource() == botonTransparencia) {
                VentanaPrincipal.this.botonTransparenciaActionPerformed(evt);
            }
            else if (evt.getSource() == botonAlisar) {
                VentanaPrincipal.this.botonAlisarActionPerformed(evt);
            }
            else if (evt.getSource() == botonRecorte) {
                VentanaPrincipal.this.botonRecorteActionPerformed(evt);
            }
            else if (evt.getSource() == botonVolcado) {
                VentanaPrincipal.this.botonVolcadoActionPerformed(evt);
            }
            else if (evt.getSource() == botonCancelar) {
                VentanaPrincipal.this.botonCancelarActionPerformed(evt);
            }
            else if (evt.getSource() == botonRecortar) {
                VentanaPrincipal.this.botonRecortarActionPerformed(evt);
            }
            else if (evt.getSource() == botonRedimensionar) {
                VentanaPrincipal.this.botonRedimensionarActionPerformed(evt);
            }
            else if (evt.getSource() == menuNuevo) {
                VentanaPrincipal.this.menuNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == menuAbrir) {
                VentanaPrincipal.this.menuAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == menuGuardar) {
                VentanaPrincipal.this.menuGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == menuBarraEstado) {
                VentanaPrincipal.this.menuBarraEstadoActionPerformed(evt);
            }
            else if (evt.getSource() == menuBarraFormas) {
                VentanaPrincipal.this.menuBarraFormasActionPerformed(evt);
            }
            else if (evt.getSource() == menuBarraAtributos) {
                VentanaPrincipal.this.menuBarraAtributosActionPerformed(evt);
            }
            else if (evt.getSource() == menuTamanio) {
                VentanaPrincipal.this.menuTamanioActionPerformed(evt);
            }
            else if (evt.getSource() == menuRescaleOp) {
                VentanaPrincipal.this.menuRescaleOpActionPerformed(evt);
            }
            else if (evt.getSource() == menuConvolveOp) {
                VentanaPrincipal.this.menuConvolveOpActionPerformed(evt);
            }
            else if (evt.getSource() == menuAffineTransfomOp) {
                VentanaPrincipal.this.menuAffineTransfomOpActionPerformed(evt);
            }
            else if (evt.getSource() == menuLookupOp) {
                VentanaPrincipal.this.menuLookupOpActionPerformed(evt);
            }
            else if (evt.getSource() == botonIluminarZonasOscuras) {
                VentanaPrincipal.this.botonIluminarZonasOscurasActionPerformed(evt);
            }
        }

        public void focusGained(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == sliderBrillo) {
                VentanaPrincipal.this.sliderBrilloFocusGained(evt);
            }
            else if (evt.getSource() == sliderRotacion) {
                VentanaPrincipal.this.sliderRotacionFocusGained(evt);
            }
        }

        public void focusLost(java.awt.event.FocusEvent evt) {
            if (evt.getSource() == sliderBrillo) {
                VentanaPrincipal.this.sliderBrilloFocusLost(evt);
            }
            else if (evt.getSource() == sliderRotacion) {
                VentanaPrincipal.this.sliderRotacionFocusLost(evt);
            }
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseMoved(evt);
            }
            else if (evt.getSource() == escritorio) {
                VentanaPrincipal.this.escritorioMouseMoved(evt);
            }
        }

        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (evt.getSource() == sliderBrillo) {
                VentanaPrincipal.this.sliderBrilloStateChanged(evt);
            }
            else if (evt.getSource() == sliderRotacion) {
                VentanaPrincipal.this.sliderRotacionStateChanged(evt);
            }
            else if (evt.getSource() == botonGrosor) {
                VentanaPrincipal.this.botonGrosorStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img;
        img = new BufferedImage(300, 300, BufferedImage.TYPE_INT_ARGB);
        vi.getLienzo2D().addMouseMotionListener(new ManejadorRaton());
        vi.getLienzo2D().setImage(img);
        img.getGraphics().setColor(Color.WHITE);
        img.getGraphics().fillRect(img.getMinX(), img.getMinY(), img.getWidth(), img.getHeight());
        this.InicializarVentana(vi);
        //2) Crear el objeto manejador (hacer el "new" de la clase anterior)
        //3) Enlazar el generador con el manejador
        vi.addInternalFrameListener(new ManejadorVentanaInterna());
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("punto");
        }
        barraEstado.setText("Punto");
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLineaActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("linea");
        }
        barraEstado.setText("Linea");
    }//GEN-LAST:event_botonLineaActionPerformed

    private void botonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRectanguloActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("rectangulo");
        }
        barraEstado.setText("Rectangulo");
    }//GEN-LAST:event_botonRectanguloActionPerformed

    private void botonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElipseActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("elipse");
        }
        barraEstado.setText("Elipse");
    }//GEN-LAST:event_botonElipseActionPerformed

    private void botonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRellenoActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setRelleno(!vi.getLienzo2D().isRelleno());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonRellenoActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("seleccionar");
            barraEstado.setText("Seleccionar");
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonDesplegableColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesplegableColoresActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setColor((Color) botonDesplegableColores.getSelectedItem());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonDesplegableColoresActionPerformed

    private void botonGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonGrosorStateChanged
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setTrazo((int) botonGrosor.getValue());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonGrosorStateChanged

    private void botonAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlisarActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setAlisar(!vi.getLienzo2D().isAlisar());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonAlisarActionPerformed

    private void botonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTransparenciaActionPerformed
         VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setTransparencia(!vi.getLienzo2D().isTransparencia());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonTransparenciaActionPerformed


    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        dlg.setFileFilter(new FileNameExtensionFilter("Imagenes(jpg, jpeg, bmp, gif, png, wbmp,)", "jpg", "bmp", "gif", "png", "wbmp", "jpeg"));
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {

                File f = dlg.getSelectedFile();
                if (f.getName().lastIndexOf(".") != -1) {
                    String extension = f.getName().substring(f.getName().lastIndexOf(".") + 1);
                    if (extension.equals("jpg") || extension.equals("jpeg") || extension.equals("bmp") || extension.equals("gif") || extension.equals("png") || extension.equals("wbmp")) {

                        BufferedImage img = ImageIO.read(f);
                        VentanaInterna vi = new VentanaInterna();

                        vi.getLienzo2D().setImage(img);
                        vi.getLienzo2D().addMouseMotionListener(new ManejadorRaton());
                        this.InicializarVentana(vi);
                        this.escritorio.add(vi);
                        vi.setTitle(f.getName());
                        vi.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(dlg, "Error al abrir archivo: Formato Incompatible.", "Error de lectura", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(dlg, "Error al abrir archivo: Formato Desconocido.", "Error de lectura", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                System.err.println("Error al leer la imagen");
            }
        }

    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        BufferedImage img;
        img = new BufferedImage(300, 300, BufferedImage.TYPE_INT_RGB);
        vi.getLienzo2D().setImage(img);
        vi.getLienzo2D().addMouseMotionListener(new ManejadorRaton());
        img.getGraphics().setColor(Color.WHITE);
        img.getGraphics().fillRect(img.getMinX(), img.getMinY(), img.getWidth(), img.getHeight());
        this.InicializarVentana(vi);
        //2) Crear el objeto manejador (hacer el "new" de la clase anterior)
        //3) Enlazar el generador con el manejador
        vi.addInternalFrameListener(new ManejadorVentanaInterna());
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(true);
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                dlg.setFileFilter(new FileNameExtensionFilter("Imagenes(jpg, jpeg, bmp, gif, png, wbmp,)", "jpg", "bmp", "gif", "png", "wbmp", "jpeg"));
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();

                        String extension;
                        if (f.getName().lastIndexOf(".") != -1) {
                            extension = f.getName().substring(f.getName().lastIndexOf(".") + 1);
                            if (!(extension.equals("jpg") || extension.equals("jpeg") || extension.equals("bmp") || extension.equals("gif") || extension.equals("png") || extension.equals("wbmp"))) {
                                JOptionPane.showMessageDialog(dlg, "Error al guardar archivo: Formato Incompatible.", "Error de Guardado", JOptionPane.ERROR_MESSAGE);
                            } else {
                                vi.setTitle(f.getName());
                            }
                        } else {
                            extension = "jpg";
                            vi.setTitle(f.getName());
                        }

                        ImageIO.write(img, extension, f);

                    } catch (Exception ex) {

                        System.err.println("Error al guardar la imagen");
                        JOptionPane.showMessageDialog(dlg, "Error al guardar archivo.", "Error de Guardado", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(true);
            if (img != null) {
                JFileChooser dlg = new JFileChooser();
                dlg.setFileFilter(new FileNameExtensionFilter("Imagenes(jpg, jpeg, bmp, gif, png, wbmp,)", "jpg", "bmp", "gif", "png", "wbmp", "jpeg"));
                int resp = dlg.showSaveDialog(this);
                if (resp == JFileChooser.APPROVE_OPTION) {
                    try {
                        File f = dlg.getSelectedFile();

                        String extension;
                        if (f.getName().lastIndexOf(".") != -1) {
                            extension = f.getName().substring(f.getName().lastIndexOf(".") + 1);
                            if (!(extension.equals("jpg") || extension.equals("jpeg") || extension.equals("bmp") || extension.equals("gif") || extension.equals("png") || extension.equals("wbmp"))) {
                                JOptionPane.showMessageDialog(dlg, "Error al guardar archivo: Formato Incompatible.", "Error de Guardado", JOptionPane.ERROR_MESSAGE);
                            } else {
                                vi.setTitle(f.getName());
                            }
                        } else {
                            extension = "jpg";
                            vi.setTitle(f.getName());
                        }

                        ImageIO.write(img, extension, f);

                    } catch (Exception ex) {

                        System.err.println("Error al guardar la imagen");
                        JOptionPane.showMessageDialog(dlg, "Error al guardar archivo.", "Error de Guardado", JOptionPane.ERROR_MESSAGE);
                    }
                }
            }
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        dlg.setFileFilter(new FileNameExtensionFilter("Imagenes(jpg, jpeg, bmp, gif, png, wbmp,)", "jpg", "bmp", "gif", "png", "wbmp", "jpeg"));
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            try {

                File f = dlg.getSelectedFile();
                if (f.getName().lastIndexOf(".") != -1) {
                    String extension = f.getName().substring(f.getName().lastIndexOf(".") + 1);
                    if (extension.equals("jpg") || extension.equals("jpeg") || extension.equals("bmp") || extension.equals("gif") || extension.equals("png") || extension.equals("wbmp")) {

                        BufferedImage img = ImageIO.read(f);
                        VentanaInterna vi = new VentanaInterna();

                        vi.getLienzo2D().setImage(img);
                        vi.getLienzo2D().addMouseMotionListener(new ManejadorRaton());
                        this.InicializarVentana(vi);
                        this.escritorio.add(vi);
                        vi.setTitle(f.getName());
                        vi.setVisible(true);

                    } else {
                        JOptionPane.showMessageDialog(dlg, "Error al abrir archivo: Formato Incompatible.", "Error de lectura", JOptionPane.ERROR_MESSAGE);
                    }
                } else {
                    JOptionPane.showMessageDialog(dlg, "Error al abrir archivo: Formato Desconocido.", "Error de lectura", JOptionPane.ERROR_MESSAGE);
                }

            } catch (Exception ex) {
                System.err.println("Error al leer la imagen");
            }
        }
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void menuBarraAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarraAtributosActionPerformed
        barraAtributos.setVisible(menuBarraAtributos.isSelected());
    }//GEN-LAST:event_menuBarraAtributosActionPerformed

    private void menuBarraFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarraFormasActionPerformed
        barraFormas.setVisible(menuBarraFormas.isSelected());
    }//GEN-LAST:event_menuBarraFormasActionPerformed

    private void menuBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarraEstadoActionPerformed
        barraEstado.setVisible(menuBarraEstado.isSelected());
    }//GEN-LAST:event_menuBarraEstadoActionPerformed

    private void escritorioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escritorioMouseMoved
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi!=null)
        vi.addMouseMotionListener(new ManejadorRaton());
        
    }//GEN-LAST:event_escritorioMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formMouseMoved

    private void botonRecorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecorteActionPerformed
           VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setRecorte(!vi.getLienzo2D().isRecorte());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonRecorteActionPerformed

    private void botonVolcadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolcadoActionPerformed
          VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().volcar();
            vi.getLienzo2D().repaint();
        }
        
    }//GEN-LAST:event_botonVolcadoActionPerformed

    private void menuTamanioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuTamanioActionPerformed
        // TODO add your handling code here:

        double x = this.getLocationOnScreen().getX() + (this.getWidth() / 2);
        double y = this.getLocationOnScreen().getY() + (this.getHeight() / 2);
        ventanaTamanio.setLocation((int) x - ventanaTamanio.getWidth() / 2, (int) y - ventanaTamanio.getHeight() / 2);

        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            alto.setValue(Integer.valueOf(vi.getLienzo2D().getImage(true).getHeight()));
            ancho.setValue(Integer.valueOf(vi.getLienzo2D().getImage(true).getWidth()));

        }
        ventanaTamanio.setVisible(true);

    }//GEN-LAST:event_menuTamanioActionPerformed

    private void botonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCancelarActionPerformed
        // TODO add your handling code here:
        ventanaTamanio.dispose();
    }//GEN-LAST:event_botonCancelarActionPerformed

    private void botonRedimensionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRedimensionarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        BufferedImage img = vi.getLienzo2D().getImage(false);
        BufferedImage imgr = new BufferedImage((int) ancho.getValue(), (int) alto.getValue(), BufferedImage.TYPE_INT_ARGB);
        imgr.getGraphics().drawImage(img, 0, 0, (int) ancho.getValue(), (int) alto.getValue(), null);

        vi.getLienzo2D().setImage(imgr);
        vi.getLienzo2D().repaint();


    }//GEN-LAST:event_botonRedimensionarActionPerformed

    private void botonRecortarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRecortarActionPerformed
        // TODO add your handling code here:
        VentanaInterna vi = (VentanaInterna) escritorio.getSelectedFrame();
        BufferedImage img = vi.getLienzo2D().getImage(false);
        BufferedImage imgr = new BufferedImage((int) ancho.getValue(), (int) alto.getValue(), BufferedImage.TYPE_INT_ARGB);
        imgr.getGraphics().drawImage(img, 0, 0, null);
        vi.getLienzo2D().setImage(imgr);
        vi.getLienzo2D().repaint();

    }//GEN-LAST:event_botonRecortarActionPerformed

    private void menuRescaleOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuRescaleOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (img != null) {
                try {
                    RescaleOp rop = new RescaleOp(1.0F, 100.0F, null);
                    rop.filter(img, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_menuRescaleOpActionPerformed

    private void menuConvolveOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuConvolveOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (img != null) {
                try {
                    float filtro[] = {0.1f, 0.1f, 0.1f, 0.1f, 0.2f, 0.1f, 0.1f, 0.1f, 0.1f};
                    Kernel k = new Kernel(3, 3, filtro);
                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgd = cop.filter(img, null);
                    vi.getLienzo2D().setImage(imgd);
                    vi.getLienzo2D().repaint();

                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_menuConvolveOpActionPerformed

    private void sliderBrilloStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderBrilloStateChanged
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (imgFuente != null) {
                try {
                    int brillo = this.sliderBrillo.getValue();
                    float escalas[] = {1.0f, 1.0f, 1.0f, 1.0f};
                    RescaleOp rop;
                    if (img.getAlphaRaster() != null) {
                        float offsets[] = {(float) brillo, (float) brillo, (float) brillo, 0.0f};
                        rop = new RescaleOp(escalas, offsets, null);
                    } else {
                        rop = new RescaleOp(1.0f, brillo, null);
                    }

                    rop.filter(imgFuente, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_sliderBrilloStateChanged

    private void sliderBrilloFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderBrilloFocusGained
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if (botonAplicarOperaciones.isSelected()) {
                vi.getLienzo2D().volcar();
            }
            ColorModel cm = vi.getLienzo2D().getImage(false).getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImage(false).copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImage(false).isAlphaPremultiplied();
            imgFuente = new BufferedImage(cm, raster, alfaPre, null);
        }
    }//GEN-LAST:event_sliderBrilloFocusGained

    private void sliderBrilloFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderBrilloFocusLost
        imgFuente = null;
        sliderBrillo.setValue(0);
    }//GEN-LAST:event_sliderBrilloFocusLost

    private void seleccionMascaraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionMascaraActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if (botonAplicarOperaciones.isSelected()) {
                vi.getLienzo2D().volcar();
            }
            BufferedImage img = vi.getLienzo2D().getImage(false);

            int seleccion = this.seleccionMascara.getSelectedIndex();
            Kernel k = this.getKernel(seleccion);

            if (img != null && k != null) {
                try {

                    ConvolveOp cop = new ConvolveOp(k);
                    BufferedImage imgd = cop.filter(img, null);
                    vi.getLienzo2D().setImage(imgd);
                    vi.getLienzo2D().repaint();

                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_seleccionMascaraActionPerformed

    private void menuLookupOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLookupOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (img != null) {
                try {
                    byte funcionT[] = new byte[256];
                    for (int x = 0; x < 256; x++) {
                        funcionT[x] = (byte) (255 - x); // Negativo
                    }
                    LookupTable tabla = new ByteLookupTable(0, funcionT);
                    LookupOp lop = new LookupOp(tabla, null);
                    lop.filter(img, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_menuLookupOpActionPerformed

    private void menuAffineTransfomOpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAffineTransfomOpActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (img != null) {
                try {
                    //AffineTransform at = AffineTransform.getScaleInstance(1.5, 1.5);
                    AffineTransform at = AffineTransform.getRotateInstance(Math.toRadians(45), img.getWidth()/2, img.getHeight()/2);
                    AffineTransformOp atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }//GEN-LAST:event_menuAffineTransfomOpActionPerformed

    private void botonContrasteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonContrasteActionPerformed
        LookupTable tabla = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_SFUNCION);
        aplicarLookup(tabla);
    }//GEN-LAST:event_botonContrasteActionPerformed

    private void botonOscurecerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonOscurecerActionPerformed
        LookupTable tabla = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_POWER);
        aplicarLookup(tabla);
    }//GEN-LAST:event_botonOscurecerActionPerformed

    private void botonIluminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIluminarActionPerformed
        LookupTable tabla = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_LOGARITHM);
        aplicarLookup(tabla);
    }//GEN-LAST:event_botonIluminarActionPerformed

    private void botonCuadraticaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCuadraticaActionPerformed
        LookupTable tabla = QuadraticFunction((double)sliderCuadratico.getValue());
        aplicarLookup(tabla);
    }//GEN-LAST:event_botonCuadraticaActionPerformed

    private void boton180ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton180ActionPerformed
         this.Rotar(180);
    }//GEN-LAST:event_boton180ActionPerformed

    private void boton90ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton90ActionPerformed
        this.Rotar(90);
    }//GEN-LAST:event_boton90ActionPerformed

    private void boton270ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boton270ActionPerformed
        this.Rotar(270);
    }//GEN-LAST:event_boton270ActionPerformed

    private void sliderRotacionStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sliderRotacionStateChanged
        /*
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if (imgFuente != null) {
                try {
                    AffineTransform at = AffineTransform.getRotateInstance(Math.toRadians(sliderRotacion.getValue()), imgFuente.getWidth()/2, imgFuente.getHeight()/2);
                    AffineTransformOp atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(imgFuente, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                    
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
        */
        
                VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if (imgFuente != null) {
                try {
                    
                    
                    AffineTransform at_rot = AffineTransform.getRotateInstance(Math.toRadians(sliderRotacion.getValue()), imgFuente.getWidth()/2, imgFuente.getHeight()/2);
                    AffineTransformOp atop = new AffineTransformOp(at_rot, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdestaux = atop.filter(imgFuente, null);
                    double restax = abs(imgdestaux.getWidth()-imgFuente.getWidth());
                    double restay = abs(imgdestaux.getHeight()-imgFuente.getHeight());
                    AffineTransform at_tras = AffineTransform.getTranslateInstance(restax, restay);
                    AffineTransformOp atop_aux = new AffineTransformOp(at_tras, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop_aux.filter(imgFuente, null);
                    AffineTransform at_rot_aux = AffineTransform.getRotateInstance(Math.toRadians(sliderRotacion.getValue()), (imgFuente.getWidth()/2)+restax, (imgFuente.getHeight()/2)+restay);
                    atop = new AffineTransformOp(at_rot_aux, AffineTransformOp.TYPE_BILINEAR);
                    imgdest = atop.filter(imgdest, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                    
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
        
    }//GEN-LAST:event_sliderRotacionStateChanged

    private void sliderRotacionFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderRotacionFocusGained
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            this.imgFuente = vi.getLienzo2D().getImage(false); 
        }
    }//GEN-LAST:event_sliderRotacionFocusGained

    private void sliderRotacionFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_sliderRotacionFocusLost
        this.imgFuente = null;
        this.sliderRotacion.setValue(0);
    }//GEN-LAST:event_sliderRotacionFocusLost

    private void botonAmpliarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAmpliarActionPerformed
        this.Escalar(1.25);
    }//GEN-LAST:event_botonAmpliarActionPerformed

    private void botonReduccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonReduccionActionPerformed
         this.Escalar(0.75);
    }//GEN-LAST:event_botonReduccionActionPerformed

    private void botonNegativoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNegativoActionPerformed
        LookupTable tabla = LookupTableProducer.createLookupTable(LookupTableProducer.TYPE_NEGATIVE);
        aplicarLookup(tabla);
    }//GEN-LAST:event_botonNegativoActionPerformed

    private void botonDuplicarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDuplicarActionPerformed
        VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            if (botonAplicarOperaciones.isSelected()) {
                vi.getLienzo2D().volcar();
            }
            ColorModel cm = vi.getLienzo2D().getImage(false).getColorModel();
            WritableRaster raster = vi.getLienzo2D().getImage(false).copyData(null);
            boolean alfaPre = vi.getLienzo2D().getImage(false).isAlphaPremultiplied();
            VentanaInterna vi_aux = new VentanaInterna();
            
            vi_aux.setVisible(true);
            BufferedImage img;
            img = new BufferedImage(cm, raster, alfaPre, null);
            vi_aux.getLienzo2D().addMouseMotionListener(new ManejadorRaton());
            vi_aux.getLienzo2D().setImage(img);
            this.InicializarVentana(vi_aux);
            escritorio.add(vi_aux);
            //2) Crear el objeto manejador (hacer el "new" de la clase anterior)
            //3) Enlazar el generador con el manejador
            vi_aux.addInternalFrameListener(new ManejadorVentanaInterna());

        }
        
 
    }//GEN-LAST:event_botonDuplicarActionPerformed

    private void botonIluminarZonasOscurasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonIluminarZonasOscurasActionPerformed
        LookupTable tabla = IluminarZonasOscuras();
        aplicarLookup(tabla);
    }//GEN-LAST:event_botonIluminarZonasOscurasActionPerformed

    
    private void Escalar (double esc)
    {
               VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (img != null) {
                try {
                    AffineTransform at = AffineTransform.getScaleInstance(esc, esc);
                    AffineTransformOp atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }
    private void Rotar (int grados)
    {
         VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (img != null) {
                try {
                    AffineTransform at = AffineTransform.getRotateInstance(Math.toRadians(grados), img.getWidth()/2, img.getHeight()/2);
                    AffineTransformOp atop = new AffineTransformOp(at, AffineTransformOp.TYPE_BILINEAR);
                    BufferedImage imgdest = atop.filter(img, null);
                    vi.getLienzo2D().setImage(imgdest);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }
    
    private static LookupTable QuadraticFunction (double m) {
        double Max; 
        if (m>=128)        
            Max = (1.0/100)*Math.pow(0.0-m,2);
        else
            Max = (1.0/100)*Math.pow(255.0-m,2);
        double K = 255.0 / Max;
        byte lt[] = new byte[256];
        for (int x = 0; x < 256; x++) {
            lt[x] = (byte) (K*(1.0/100.0)*Math.pow((double)x-m,2));
        }
        ByteLookupTable slt = new ByteLookupTable(0, lt);
        return slt;
    }
    
     private static LookupTable IluminarZonasOscuras () {
        double Max, Max2; 
                
            Max = 255.0;
            Max2 = Math.log(1.0+(double)128.0);
            
        double K = 128.0 / Max2;
        byte lt[] = new byte[256];
        for (int x = 0; x < 256; x++) {
            if (x >= 128)
                lt[x] = (byte)x;
            else
                lt[x] = (byte) ((double)K*Math.log(1.0+(double)x));
        }
        ByteLookupTable slt = new ByteLookupTable(0, lt);
        return slt;
    }
    
    private void aplicarLookup (LookupTable tabla)
    {
         VentanaInterna vi = (VentanaInterna) (escritorio.getSelectedFrame());
        if (vi != null) {
            BufferedImage img = vi.getLienzo2D().getImage(false);
            if (img != null) {
                try {
                    
                    LookupOp lop = new LookupOp(tabla, null);
                    lop.filter(img, img);
                    vi.getLienzo2D().repaint();
                } catch (IllegalArgumentException e) {
                    System.err.println(e.getLocalizedMessage());
                }
            }
        }
    }
    private Kernel getKernel(int seleccion){
        Kernel k = null;
        float[] filtro;
            switch (seleccion){
                case 0:
                    k =KernelProducer.createKernel(KernelProducer.TYPE_MEDIA_3x3);
                    break;
                case 1:
                    k =KernelProducer.createKernel(KernelProducer.TYPE_BINOMIAL_3x3);
                    break;
                case 2:
                    k =KernelProducer.createKernel(KernelProducer.TYPE_ENFOQUE_3x3);
                    break;
                case 3:
                    k =KernelProducer.createKernel(KernelProducer.TYPE_RELIEVE_3x3);
                    break;
                case 4:
                    k =KernelProducer.createKernel(KernelProducer.TYPE_LAPLACIANA_3x3);
                    break;
                case 5:
                    filtro = new float[]{0.1f,0.1f,0.1f,0.1f,0.1f,0.1f,0.1f,0.1f,0.1f,0.1f}; //10*1
                    k= new Kernel(10, 1, filtro);
                    break;
                case 6:
                    //filtro = new float[]{0.25f,0.25f,0.25f,0.25f};
                    filtro = new float[]{0.25f, 0.0f, 0.0f, 0.0f,
                                         0.0f, 0.25f, 0.0f, 0.0f,
                                         0.0f, 0.0f,  0.25f, 0.0f,
                                         0.0f, 0.0f,  0.0f,  0.25f};
                    k= new Kernel(4, 4, filtro);
                    break;   
            
            }
            return k;
    }
    private void InicializarVentana(VentanaInterna vi)
    {
        barraEstado.setText("Punto");
        vi.getLienzo2D().setHerramienta("punto");
        vi.getLienzo2D().setColor(Color.BLACK);
        botonDesplegableColores.setSelectedItem(Color.BLACK);
        botonPunto.setSelected(true);
        botonAlisar.setSelected(false);
        botonTransparencia.setSelected(false);
        botonRelleno.setSelected(false);
        botonRecorte.setSelected(false);
        botonGrosor.setValue((int) 3);
        vi.getLienzo2D().setTrazo(3);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    //1) Definir la clase manejadora y sobrecargar los metodos que sean necesarios
    private class ManejadorVentanaInterna extends InternalFrameAdapter {

        public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            VentanaInterna vi = (VentanaInterna) evt.getInternalFrame();
            botonRelleno.setSelected(vi.getLienzo2D().isRelleno());
            botonTransparencia.setSelected(vi.getLienzo2D().isTransparencia());
            botonAlisar.setSelected(vi.getLienzo2D().isAlisar());
            botonRecorte.setSelected(vi.getLienzo2D().isRecorte());
            botonDesplegableColores.setSelectedItem(vi.getLienzo2D().getColor());
            botonGrosor.setValue(vi.getLienzo2D().getTrazo());
            
            switch (vi.getLienzo2D().getHerramienta()) {
                case "punto":
                    botonPunto.setSelected(true);
                    barraEstado.setText("Punto");
                    break;
                case "linea":
                    botonLinea.setSelected(true);
                    barraEstado.setText("Linea");
                    break;
                case "rectangulo":
                    botonRectangulo.setSelected(true);
                    barraEstado.setText("Rectangulo");
                    break;
                case "elipse":
                    botonElipse.setSelected(true);
                    barraEstado.setText("Elipse");
                    break;
                case "seleccionar":
                    botonSeleccionar.setSelected(true);
                    barraEstado.setText("Seleccionar");
                    break;
            }

        }
        
    }
    
  private class ManejadorRaton extends MouseMotionAdapter {
      public void mouseMoved(java.awt.event.MouseEvent evt) {
          Point p = new Point (evt.getPoint());
          barraCoordenadas.setText("x: "+p.getX()+", y: "+p.getY());
      }
  }   
          
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotonesHerramientas;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JPanel PanelCentral;
    private javax.swing.JSpinner alto;
    private javax.swing.JSpinner ancho;
    private javax.swing.JToolBar barraAtributos;
    private javax.swing.JLabel barraCoordenadas;
    private javax.swing.JLabel barraEstado;
    private javax.swing.JToolBar barraFormas;
    private javax.swing.JToolBar barraOpcionesImagen;
    private javax.swing.JButton boton180;
    private javax.swing.JButton boton270;
    private javax.swing.JButton boton90;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JToggleButton botonAlisar;
    private javax.swing.JButton botonAmpliar;
    private javax.swing.JToggleButton botonAplicarOperaciones;
    private javax.swing.JButton botonCancelar;
    private javax.swing.JButton botonContraste;
    private javax.swing.JButton botonCuadratica;
    private javax.swing.JComboBox<Color> botonDesplegableColores;
    private javax.swing.JButton botonDuplicar;
    private javax.swing.JToggleButton botonElipse;
    private javax.swing.JSpinner botonGrosor;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JButton botonIluminar;
    private javax.swing.JButton botonIluminarZonasOscuras;
    private javax.swing.JToggleButton botonLinea;
    private javax.swing.JButton botonNegativo;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JButton botonOscurecer;
    private javax.swing.JToggleButton botonPunto;
    private javax.swing.JButton botonRecortar;
    private javax.swing.JToggleButton botonRecorte;
    private javax.swing.JToggleButton botonRectangulo;
    private javax.swing.JButton botonRedimensionar;
    private javax.swing.JButton botonReduccion;
    private javax.swing.JToggleButton botonRelleno;
    private javax.swing.JToggleButton botonSeleccionar;
    private javax.swing.JToggleButton botonTransparencia;
    private javax.swing.JButton botonVolcado;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenuItem menuAffineTransfomOp;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JCheckBoxMenuItem menuBarraAtributos;
    private javax.swing.JCheckBoxMenuItem menuBarraEstado;
    private javax.swing.JCheckBoxMenuItem menuBarraFormas;
    private javax.swing.JMenuItem menuConvolveOp;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenu menuImagen;
    private javax.swing.JMenuItem menuLookupOp;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JMenuItem menuRescaleOp;
    private javax.swing.JMenuItem menuTamanio;
    private javax.swing.JPanel panelBrillo;
    private javax.swing.JPanel panelContraste;
    private javax.swing.JPanel panelCuadratico;
    private javax.swing.JPanel panelEscalado;
    private javax.swing.JPanel panelEstados;
    private javax.swing.JPanel panelFiltros;
    private javax.swing.JPanel panelHerramientas;
    private javax.swing.JPanel panelImageOp;
    private javax.swing.JPanel panelRotacion;
    private javax.swing.JComboBox<String> seleccionMascara;
    private javax.swing.JSlider sliderBrillo;
    private javax.swing.JSlider sliderCuadratico;
    private javax.swing.JSlider sliderRotacion;
    private javax.swing.JDialog ventanaTamanio;
    // End of variables declaration//GEN-END:variables
}
