/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica6;

import java.awt.GraphicsEnvironment;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author carlo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(700,700);
        
        GraphicsEnvironment ge;
        ge = GraphicsEnvironment.getLocalGraphicsEnvironment();
        String[] fuentesSistema = ge.getAvailableFontFamilyNames();
        listaFuentes.setModel(new DefaultComboBoxModel(fuentesSistema));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        BotonMover = new javax.swing.JCheckBox();
        BotonRelleno = new javax.swing.JCheckBox();
        listaFuentes = new javax.swing.JComboBox<>();
        BotonRecorte = new javax.swing.JCheckBox();
        lienzo1 = new practica6.Lienzo();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        BotonMover.setText("Mover");
        BotonMover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonMoverActionPerformed(evt);
            }
        });
        jPanel1.add(BotonMover);

        BotonRelleno.setText("Relleno");
        BotonRelleno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRellenoActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRelleno);

        listaFuentes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        listaFuentes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listaFuentesActionPerformed(evt);
            }
        });
        jPanel1.add(listaFuentes);

        BotonRecorte.setText("Efecto Ventana");
        BotonRecorte.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotonRecorteActionPerformed(evt);
            }
        });
        jPanel1.add(BotonRecorte);

        getContentPane().add(jPanel1, java.awt.BorderLayout.SOUTH);

        javax.swing.GroupLayout lienzo1Layout = new javax.swing.GroupLayout(lienzo1);
        lienzo1.setLayout(lienzo1Layout);
        lienzo1Layout.setHorizontalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 430, Short.MAX_VALUE)
        );
        lienzo1Layout.setVerticalGroup(
            lienzo1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 261, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo1, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void listaFuentesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listaFuentesActionPerformed
        // TODO add your handling code here:
        lienzo1.setFuente((String)listaFuentes.getSelectedItem());
        lienzo1.repaint();
    }//GEN-LAST:event_listaFuentesActionPerformed

    private void BotonRecorteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRecorteActionPerformed
        // TODO add your handling code here:
        
        if (BotonRecorte.isSelected())
        {
            lienzo1.setVentanaClipActiva(true);
        }
        else
        {
            lienzo1.setVentanaClipActiva(false);
        }
        lienzo1.repaint();
        
    }//GEN-LAST:event_BotonRecorteActionPerformed

    private void BotonMoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonMoverActionPerformed
        // TODO add your handling code here:
        
        if (BotonMover.isSelected())
        {
            lienzo1.setMoverActivo(true);
        }
        else
        {
            lienzo1.setMoverActivo(false);
        }
    }//GEN-LAST:event_BotonMoverActionPerformed

    private void BotonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotonRellenoActionPerformed
        // TODO add your handling code here:
        
        if (BotonRelleno.isSelected())
        {
            lienzo1.setRellenoActivo(true);
        }
        else
        {
            lienzo1.setRellenoActivo(false);
        }
        
        lienzo1.repaint();
    }//GEN-LAST:event_BotonRellenoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox BotonMover;
    private javax.swing.JCheckBox BotonRecorte;
    private javax.swing.JCheckBox BotonRelleno;
    private javax.swing.JPanel jPanel1;
    private practica6.Lienzo lienzo1;
    private javax.swing.JComboBox<String> listaFuentes;
    // End of variables declaration//GEN-END:variables
}
