/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.awt.Point;
import sm.cgs.iu.Lienzo2D;

/**
 *
 * @author carlo
 */
public class VentanaInterna extends javax.swing.JInternalFrame {

    /**
     * Creates new form VentanaInterna
     */
    
    Point p;
    
    
    public VentanaInterna() {
        initComponents();
    }

    public Lienzo2D getLienzo2D() {
        return lienzo2D;
    }

    public void setLienzo2D(Lienzo2D lienzo2D) {
        this.lienzo2D = lienzo2D;
    }

    public Point getP() {
        return p;
    }
    
    
    
  /*  private class ManejadorLienzo extends javax.swing.event.MouseInputAdapter{
        public void mouseMoved(java.awt.event.MouseEvent evt) {
            p = evt.getPoint();
            
        }
    }
    */
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lienzo2D = new sm.cgs.iu.Lienzo2D();

        FormListener formListener = new FormListener();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        lienzo2D.addMouseMotionListener(formListener);

        javax.swing.GroupLayout lienzo2DLayout = new javax.swing.GroupLayout(lienzo2D);
        lienzo2D.setLayout(lienzo2DLayout);
        lienzo2DLayout.setHorizontalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 394, Short.MAX_VALUE)
        );
        lienzo2DLayout.setVerticalGroup(
            lienzo2DLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 278, Short.MAX_VALUE)
        );

        getContentPane().add(lienzo2D, java.awt.BorderLayout.CENTER);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.MouseMotionListener {
        FormListener() {}
        public void mouseDragged(java.awt.event.MouseEvent evt) {
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == lienzo2D) {
                VentanaInterna.this.lienzo2DMouseMoved(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void lienzo2DMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lienzo2DMouseMoved
       // lienzo2D.addMouseMotionListener(new ManejadorLienzo());
        p = evt.getPoint();
        
    }//GEN-LAST:event_lienzo2DMouseMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private sm.cgs.iu.Lienzo2D lienzo2D;
    // End of variables declaration//GEN-END:variables
}
