/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package practica7;

import java.awt.BasicStroke;
import java.awt.Color;
import java.awt.Point;
import java.awt.Stroke;
import java.awt.event.MouseAdapter;
import java.io.File;
import java.util.Vector;
import javax.swing.JFileChooser;
import javax.swing.event.InternalFrameAdapter;

/**
 *
 * @author carlo
 */
public class VentanaPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form VentanaPrincipal
     */
    public VentanaPrincipal() {
        initComponents();
        this.setSize(1280, 720);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GrupoBotonesHerramientas = new javax.swing.ButtonGroup();
        jMenuItem2 = new javax.swing.JMenuItem();
        escritorio = new javax.swing.JDesktopPane();
        panelHerramientas = new javax.swing.JPanel();
        jToolBar1 = new javax.swing.JToolBar();
        botonNuevo = new javax.swing.JButton();
        botonAbrir = new javax.swing.JButton();
        botonGuardar = new javax.swing.JButton();
        barraFormas = new javax.swing.JToolBar();
        botonPunto = new javax.swing.JToggleButton();
        botonLinea = new javax.swing.JToggleButton();
        botonRectangulo = new javax.swing.JToggleButton();
        botonElipse = new javax.swing.JToggleButton();
        botonSeleccionar = new javax.swing.JToggleButton();
        barraAtributos = new javax.swing.JToolBar();
        Color colores[] ={Color.BLACK, Color.RED, Color.BLUE, Color.GREEN, Color.YELLOW, Color.WHITE};
        botonDesplegableColores = new javax.swing.JComboBox<>(colores);
        botonGrosor = new javax.swing.JSpinner();
        botonRelleno = new javax.swing.JToggleButton();
        botonTransparencia = new javax.swing.JToggleButton();
        botonAlisar = new javax.swing.JToggleButton();
        jPanel1 = new javax.swing.JPanel();
        barraCoordenadas = new javax.swing.JLabel();
        barraEstado = new javax.swing.JLabel();
        Menu = new javax.swing.JMenuBar();
        menuArchivo = new javax.swing.JMenu();
        menuNuevo = new javax.swing.JMenuItem();
        menuAbrir = new javax.swing.JMenuItem();
        menuGuardar = new javax.swing.JMenuItem();
        menuEdicion = new javax.swing.JMenu();
        menuBarraEstado = new javax.swing.JCheckBoxMenuItem();
        menuBarraFormas = new javax.swing.JCheckBoxMenuItem();
        menuBarraAtributos = new javax.swing.JCheckBoxMenuItem();

        FormListener formListener = new FormListener();

        jMenuItem2.setText("jMenuItem2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addMouseMotionListener(formListener);

        escritorio.addMouseMotionListener(formListener);

        javax.swing.GroupLayout escritorioLayout = new javax.swing.GroupLayout(escritorio);
        escritorio.setLayout(escritorioLayout);
        escritorioLayout.setHorizontalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        escritorioLayout.setVerticalGroup(
            escritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 216, Short.MAX_VALUE)
        );

        getContentPane().add(escritorio, java.awt.BorderLayout.CENTER);

        panelHerramientas.setLayout(new javax.swing.BoxLayout(panelHerramientas, javax.swing.BoxLayout.LINE_AXIS));

        jToolBar1.setRollover(true);
        jToolBar1.setPreferredSize(new java.awt.Dimension(150, 32));

        botonNuevo.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\nuevo.png")); // NOI18N
        botonNuevo.setToolTipText("Nuevo");
        botonNuevo.setFocusable(false);
        botonNuevo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonNuevo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonNuevo.addActionListener(formListener);
        jToolBar1.add(botonNuevo);

        botonAbrir.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\abrir.png")); // NOI18N
        botonAbrir.setToolTipText("Abrir");
        botonAbrir.setFocusable(false);
        botonAbrir.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAbrir.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAbrir.addActionListener(formListener);
        jToolBar1.add(botonAbrir);

        botonGuardar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\guardar.png")); // NOI18N
        botonGuardar.setToolTipText("Guardar");
        botonGuardar.setFocusable(false);
        botonGuardar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonGuardar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonGuardar.addActionListener(formListener);
        jToolBar1.add(botonGuardar);

        panelHerramientas.add(jToolBar1);

        barraFormas.setRollover(true);
        barraFormas.setPreferredSize(new java.awt.Dimension(200, 32));

        GrupoBotonesHerramientas.add(botonPunto);
        botonPunto.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\punto.png")); // NOI18N
        botonPunto.setToolTipText("Punto");
        botonPunto.setFocusable(false);
        botonPunto.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonPunto.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonPunto.addActionListener(formListener);
        barraFormas.add(botonPunto);

        GrupoBotonesHerramientas.add(botonLinea);
        botonLinea.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\linea.png")); // NOI18N
        botonLinea.setToolTipText("Linea");
        botonLinea.setFocusable(false);
        botonLinea.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonLinea.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonLinea.addActionListener(formListener);
        barraFormas.add(botonLinea);

        GrupoBotonesHerramientas.add(botonRectangulo);
        botonRectangulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\rectangulo.png")); // NOI18N
        botonRectangulo.setToolTipText("Rectangulo");
        botonRectangulo.setFocusable(false);
        botonRectangulo.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRectangulo.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRectangulo.addActionListener(formListener);
        barraFormas.add(botonRectangulo);

        GrupoBotonesHerramientas.add(botonElipse);
        botonElipse.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\elipse.png")); // NOI18N
        botonElipse.setToolTipText("Elipse");
        botonElipse.setFocusable(false);
        botonElipse.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonElipse.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonElipse.addActionListener(formListener);
        barraFormas.add(botonElipse);

        GrupoBotonesHerramientas.add(botonSeleccionar);
        botonSeleccionar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\seleccion.png")); // NOI18N
        botonSeleccionar.setToolTipText("Seleccionar");
        botonSeleccionar.setFocusable(false);
        botonSeleccionar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonSeleccionar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonSeleccionar.addActionListener(formListener);
        barraFormas.add(botonSeleccionar);

        panelHerramientas.add(barraFormas);

        barraAtributos.setRollover(true);
        barraAtributos.setPreferredSize(new java.awt.Dimension(250, 32));

        botonDesplegableColores.setToolTipText("Colores");
        botonDesplegableColores.setRenderer(new ColorCellRender());
        botonDesplegableColores.addActionListener(formListener);
        barraAtributos.add(botonDesplegableColores);

        botonGrosor.setModel(new javax.swing.SpinnerNumberModel(3, 1, null, 1));
        botonGrosor.setToolTipText("Grosor");
        botonGrosor.setPreferredSize(new java.awt.Dimension(60, 26));
        botonGrosor.addChangeListener(formListener);
        barraAtributos.add(botonGrosor);

        botonRelleno.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\rellenar.png")); // NOI18N
        botonRelleno.setToolTipText("Relleno");
        botonRelleno.setFocusable(false);
        botonRelleno.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonRelleno.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonRelleno.addActionListener(formListener);
        barraAtributos.add(botonRelleno);

        botonTransparencia.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\transparencia.png")); // NOI18N
        botonTransparencia.setToolTipText("Transparencia");
        botonTransparencia.setFocusable(false);
        botonTransparencia.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonTransparencia.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonTransparencia.addActionListener(formListener);
        barraAtributos.add(botonTransparencia);

        botonAlisar.setIcon(new javax.swing.ImageIcon("C:\\Users\\carlo\\Documents\\NetBeansProjects\\Practica7\\images\\alisar.png")); // NOI18N
        botonAlisar.setToolTipText("Alisado");
        botonAlisar.setFocusable(false);
        botonAlisar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        botonAlisar.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        botonAlisar.addActionListener(formListener);
        barraAtributos.add(botonAlisar);

        panelHerramientas.add(barraAtributos);

        getContentPane().add(panelHerramientas, java.awt.BorderLayout.PAGE_START);

        jPanel1.setPreferredSize(new java.awt.Dimension(1550, 25));
        jPanel1.setLayout(new java.awt.BorderLayout());

        barraCoordenadas.setText("Coordenadas");
        jPanel1.add(barraCoordenadas, java.awt.BorderLayout.EAST);

        barraEstado.setText("Barra de Estado");
        jPanel1.add(barraEstado, java.awt.BorderLayout.LINE_START);

        getContentPane().add(jPanel1, java.awt.BorderLayout.PAGE_END);

        menuArchivo.setText("Archivo");

        menuNuevo.setText("Nuevo");
        menuNuevo.addActionListener(formListener);
        menuArchivo.add(menuNuevo);

        menuAbrir.setText("Abrir");
        menuAbrir.addActionListener(formListener);
        menuArchivo.add(menuAbrir);

        menuGuardar.setText("Guardar");
        menuGuardar.addActionListener(formListener);
        menuArchivo.add(menuGuardar);

        Menu.add(menuArchivo);

        menuEdicion.setText("Edicion");

        menuBarraEstado.setSelected(true);
        menuBarraEstado.setText("Ver barra de estado");
        menuBarraEstado.addActionListener(formListener);
        menuEdicion.add(menuBarraEstado);

        menuBarraFormas.setSelected(true);
        menuBarraFormas.setText("Ver barra de formas");
        menuBarraFormas.addActionListener(formListener);
        menuEdicion.add(menuBarraFormas);

        menuBarraAtributos.setSelected(true);
        menuBarraAtributos.setText("Ver barra de atributos");
        menuBarraAtributos.addActionListener(formListener);
        menuEdicion.add(menuBarraAtributos);

        Menu.add(menuEdicion);

        setJMenuBar(Menu);

        pack();
    }

    // Code for dispatching events from components to event handlers.

    private class FormListener implements java.awt.event.ActionListener, java.awt.event.MouseMotionListener, javax.swing.event.ChangeListener {
        FormListener() {}
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            if (evt.getSource() == botonNuevo) {
                VentanaPrincipal.this.botonNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == botonAbrir) {
                VentanaPrincipal.this.botonAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == botonGuardar) {
                VentanaPrincipal.this.botonGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == botonPunto) {
                VentanaPrincipal.this.botonPuntoActionPerformed(evt);
            }
            else if (evt.getSource() == botonLinea) {
                VentanaPrincipal.this.botonLineaActionPerformed(evt);
            }
            else if (evt.getSource() == botonRectangulo) {
                VentanaPrincipal.this.botonRectanguloActionPerformed(evt);
            }
            else if (evt.getSource() == botonElipse) {
                VentanaPrincipal.this.botonElipseActionPerformed(evt);
            }
            else if (evt.getSource() == botonSeleccionar) {
                VentanaPrincipal.this.botonSeleccionarActionPerformed(evt);
            }
            else if (evt.getSource() == botonDesplegableColores) {
                VentanaPrincipal.this.botonDesplegableColoresActionPerformed(evt);
            }
            else if (evt.getSource() == botonRelleno) {
                VentanaPrincipal.this.botonRellenoActionPerformed(evt);
            }
            else if (evt.getSource() == botonTransparencia) {
                VentanaPrincipal.this.botonTransparenciaActionPerformed(evt);
            }
            else if (evt.getSource() == botonAlisar) {
                VentanaPrincipal.this.botonAlisarActionPerformed(evt);
            }
            else if (evt.getSource() == menuNuevo) {
                VentanaPrincipal.this.menuNuevoActionPerformed(evt);
            }
            else if (evt.getSource() == menuAbrir) {
                VentanaPrincipal.this.menuAbrirActionPerformed(evt);
            }
            else if (evt.getSource() == menuGuardar) {
                VentanaPrincipal.this.menuGuardarActionPerformed(evt);
            }
            else if (evt.getSource() == menuBarraEstado) {
                VentanaPrincipal.this.menuBarraEstadoActionPerformed(evt);
            }
            else if (evt.getSource() == menuBarraFormas) {
                VentanaPrincipal.this.menuBarraFormasActionPerformed(evt);
            }
            else if (evt.getSource() == menuBarraAtributos) {
                VentanaPrincipal.this.menuBarraAtributosActionPerformed(evt);
            }
        }

        public void mouseDragged(java.awt.event.MouseEvent evt) {
        }

        public void mouseMoved(java.awt.event.MouseEvent evt) {
            if (evt.getSource() == escritorio) {
                VentanaPrincipal.this.escritorioMouseMoved(evt);
            }
            else if (evt.getSource() == VentanaPrincipal.this) {
                VentanaPrincipal.this.formMouseMoved(evt);
            }
        }

        public void stateChanged(javax.swing.event.ChangeEvent evt) {
            if (evt.getSource() == botonGrosor) {
                VentanaPrincipal.this.botonGrosorStateChanged(evt);
            }
        }
    }// </editor-fold>//GEN-END:initComponents

    private void botonNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        vi.getLienzo2D().setHerramienta("punto");
        barraEstado.setText("Punto");
        vi.getLienzo2D().setColor(Color.BLACK);
        botonDesplegableColores.setSelectedItem(Color.BLACK);
        botonPunto.setSelected(true);
        botonAlisar.setSelected(false);
        botonTransparencia.setSelected(false);
        botonRelleno.setSelected(false);
        botonGrosor.setValue((int)3);
        vi.getLienzo2D().setTrazo(3);
        //2) Crear el objeto manejador (hacer el "new" de la clase anterior)
        //3) Enlazar el generador con el manejador
        vi.addInternalFrameListener(new ManejadorVentanaInterna());
    }//GEN-LAST:event_botonNuevoActionPerformed

    private void botonPuntoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonPuntoActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("punto");
        }
        barraEstado.setText("Punto");
    }//GEN-LAST:event_botonPuntoActionPerformed

    private void botonLineaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonLineaActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("linea");
        }
        barraEstado.setText("Linea");
    }//GEN-LAST:event_botonLineaActionPerformed

    private void botonRectanguloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRectanguloActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("rectangulo");
        }
        barraEstado.setText("Rectangulo");
    }//GEN-LAST:event_botonRectanguloActionPerformed

    private void botonElipseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonElipseActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("elipse");
        }
        barraEstado.setText("Elipse");
    }//GEN-LAST:event_botonElipseActionPerformed

    private void botonRellenoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonRellenoActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setRelleno(!vi.getLienzo2D().isRelleno());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonRellenoActionPerformed

    private void botonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSeleccionarActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setHerramienta("seleccionar");
            barraEstado.setText("Seleccionar");
        }
    }//GEN-LAST:event_botonSeleccionarActionPerformed

    private void botonDesplegableColoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonDesplegableColoresActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setColor((Color) botonDesplegableColores.getSelectedItem());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonDesplegableColoresActionPerformed

    private void botonGrosorStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_botonGrosorStateChanged
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setTrazo((int) botonGrosor.getValue());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonGrosorStateChanged

    private void botonAlisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAlisarActionPerformed
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setAlisar(!vi.getLienzo2D().isAlisar());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonAlisarActionPerformed

    private void botonTransparenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonTransparenciaActionPerformed
         VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi != null) {
            vi.getLienzo2D().setTransparencia(!vi.getLienzo2D().isTransparencia());
            vi.getLienzo2D().repaint();
        }
    }//GEN-LAST:event_botonTransparenciaActionPerformed


    private void menuAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_menuAbrirActionPerformed

    private void menuNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuNuevoActionPerformed
        VentanaInterna vi = new VentanaInterna();
        escritorio.add(vi);
        vi.setVisible(true);
        vi.getLienzo2D().setHerramienta("punto");
        barraEstado.setText("Punto");
        vi.getLienzo2D().setColor(Color.BLACK);
        botonDesplegableColores.setSelectedItem(Color.BLACK);
        botonPunto.setSelected(true);
        botonAlisar.setSelected(false);
        botonTransparencia.setSelected(false);
        botonRelleno.setSelected(false);
        botonGrosor.setValue((int)3);
        vi.getLienzo2D().setTrazo(3);
        //2) Crear el objeto manejador (hacer el "new" de la clase anterior)
        //3) Enlazar el generador con el manejador
        vi.addInternalFrameListener(new ManejadorVentanaInterna());
    }//GEN-LAST:event_menuNuevoActionPerformed

    private void menuGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuGuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Codigo
        }
    }//GEN-LAST:event_menuGuardarActionPerformed

    private void botonGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonGuardarActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showSaveDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Codigo
        }
    }//GEN-LAST:event_botonGuardarActionPerformed

    private void botonAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonAbrirActionPerformed
        JFileChooser dlg = new JFileChooser();
        int resp = dlg.showOpenDialog(this);
        if (resp == JFileChooser.APPROVE_OPTION) {
            File f = dlg.getSelectedFile();
            //Código
        }
    }//GEN-LAST:event_botonAbrirActionPerformed

    private void menuBarraAtributosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarraAtributosActionPerformed
        barraAtributos.setVisible(menuBarraAtributos.isSelected());
    }//GEN-LAST:event_menuBarraAtributosActionPerformed

    private void menuBarraFormasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarraFormasActionPerformed
        barraFormas.setVisible(menuBarraFormas.isSelected());
    }//GEN-LAST:event_menuBarraFormasActionPerformed

    private void menuBarraEstadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuBarraEstadoActionPerformed
        barraEstado.setVisible(menuBarraEstado.isSelected());
    }//GEN-LAST:event_menuBarraEstadoActionPerformed

    private void escritorioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_escritorioMouseMoved
        VentanaInterna vi;
        vi = (VentanaInterna) escritorio.getSelectedFrame();
        if (vi!=null)
        vi.addMouseMotionListener(new ManejadorRaton());
        
    }//GEN-LAST:event_escritorioMouseMoved

    private void formMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_formMouseMoved
        // TODO add your handling code here:
        
        
        
    }//GEN-LAST:event_formMouseMoved

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }

    //1) Definir la clase manejadora y sobrecargar los metodos que sean necesarios
    private class ManejadorVentanaInterna extends InternalFrameAdapter {

        public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            VentanaInterna vi = (VentanaInterna) evt.getInternalFrame();
            botonRelleno.setSelected(vi.getLienzo2D().isRelleno());
            botonTransparencia.setSelected(vi.getLienzo2D().isTransparencia());
            botonAlisar.setSelected(vi.getLienzo2D().isAlisar());
            botonDesplegableColores.setSelectedItem(vi.getLienzo2D().getColor());
            botonGrosor.setValue(vi.getLienzo2D().getTrazo());
            switch (vi.getLienzo2D().getHerramienta()) {
                case "punto":
                    botonPunto.setSelected(true);
                    barraEstado.setText("Punto");
                    break;
                case "linea":
                    botonLinea.setSelected(true);
                    barraEstado.setText("Linea");
                    break;
                case "rectangulo":
                    botonRectangulo.setSelected(true);
                    barraEstado.setText("Rectangulo");
                    break;
                case "elipse":
                    botonElipse.setSelected(true);
                    barraEstado.setText("Elipse");
                    break;
                case "seleccionar":
                    botonSeleccionar.setSelected(true);
                    barraEstado.setText("Seleccionar");
                    break;
            }

        }
        
    }
    
    private class ManejadorRaton extends MouseAdapter {
                
        public void  lienzo2DMouseMoved (java.awt.event.MouseEvent evt)
        {
            barraCoordenadas.setText(evt.getPoint().toString());
        }
        
            }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup GrupoBotonesHerramientas;
    private javax.swing.JMenuBar Menu;
    private javax.swing.JToolBar barraAtributos;
    private javax.swing.JLabel barraCoordenadas;
    private javax.swing.JLabel barraEstado;
    private javax.swing.JToolBar barraFormas;
    private javax.swing.JButton botonAbrir;
    private javax.swing.JToggleButton botonAlisar;
    private javax.swing.JComboBox<Color> botonDesplegableColores;
    private javax.swing.JToggleButton botonElipse;
    private javax.swing.JSpinner botonGrosor;
    private javax.swing.JButton botonGuardar;
    private javax.swing.JToggleButton botonLinea;
    private javax.swing.JButton botonNuevo;
    private javax.swing.JToggleButton botonPunto;
    private javax.swing.JToggleButton botonRectangulo;
    private javax.swing.JToggleButton botonRelleno;
    private javax.swing.JToggleButton botonSeleccionar;
    private javax.swing.JToggleButton botonTransparencia;
    private javax.swing.JDesktopPane escritorio;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JMenuItem menuAbrir;
    private javax.swing.JMenu menuArchivo;
    private javax.swing.JCheckBoxMenuItem menuBarraAtributos;
    private javax.swing.JCheckBoxMenuItem menuBarraEstado;
    private javax.swing.JCheckBoxMenuItem menuBarraFormas;
    private javax.swing.JMenu menuEdicion;
    private javax.swing.JMenuItem menuGuardar;
    private javax.swing.JMenuItem menuNuevo;
    private javax.swing.JPanel panelHerramientas;
    // End of variables declaration//GEN-END:variables
}
